"""
Probability calibration utilities.

Raw machine-learning probabilities are not automatically reliable.

This module provides calibration using a separate calibration
dataset, keeping calibration information isolated from the model's
training data.

Supported methods:
    - sigmoid / Platt scaling
    - isotonic regression

IMPORTANT:
Calibration must be fitted using validation/calibration data only.
The final test set must remain untouched until final evaluation.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

import numpy as np
import pandas as pd

from sklearn.isotonic import IsotonicRegression
from sklearn.linear_model import LogisticRegression


@dataclass
class CalibrationConfig:
    """Configuration for probability calibration."""

    method: str = "sigmoid"

    clip_min: float = 0.001

    clip_max: float = 0.999

    # Research-stage compatibility settings.
    min_samples: int = 50
    high_confidence_threshold: float = 0.70

    def __post_init__(self) -> None:
        if self.min_samples < 1:
            raise ValueError("min_samples must be positive.")
        if not 0.0 < self.high_confidence_threshold < 1.0:
            raise ValueError("high_confidence_threshold must be between 0 and 1.")


class ProbabilityCalibrator:
    """
    Calibrate positive-class probabilities.

    The calibrator receives probabilities generated by an already
    trained classifier and learns how those probabilities relate
    to observed outcomes.

    It does NOT retrain the original classifier.
    """

    SUPPORTED_METHODS = {
        "sigmoid",
        "isotonic",
    }

    def __init__(
        self,
        config: Optional[
            CalibrationConfig
        ] = None,
    ) -> None:

        self.config = (
            config
            if config is not None
            else CalibrationConfig()
        )

        if (
            self.config.method
            not in self.SUPPORTED_METHODS
        ):
            raise ValueError(
                "Unsupported calibration method: "
                f"{self.config.method}"
            )

        if not (
            0
            < self.config.clip_min
            < self.config.clip_max
            < 1
        ):
            raise ValueError(
                "clip_min and clip_max must satisfy "
                "0 < clip_min < clip_max < 1."
            )

        self.calibrator = (
            self._build_calibrator()
        )

        self.is_fitted_: bool = False

    def _build_calibrator(self):
        """Create the selected calibration estimator."""

        if self.config.method == "sigmoid":

            return LogisticRegression(
                C=1.0,
                max_iter=1000,
            )

        return IsotonicRegression(
            y_min=self.config.clip_min,
            y_max=self.config.clip_max,
            out_of_bounds="clip",
        )

    def _validate_probabilities(
        self,
        probabilities,
    ) -> np.ndarray:
        """Validate raw probabilities."""

        values = np.asarray(
            probabilities,
            dtype=float,
        ).reshape(-1)

        if len(values) == 0:
            raise ValueError(
                "Probability array is empty."
            )

        if not np.isfinite(
            values
        ).all():
            raise ValueError(
                "Probabilities contain non-finite values."
            )

        if (
            (values < 0).any()
            or (values > 1).any()
        ):
            raise ValueError(
                "Probabilities must be between 0 and 1."
            )

        return np.clip(
            values,
            self.config.clip_min,
            self.config.clip_max,
        )

    def _validate_targets(
        self,
        targets,
    ) -> np.ndarray:
        """Validate binary calibration targets."""

        values = np.asarray(
            targets,
        ).reshape(-1)

        if len(values) == 0:
            raise ValueError(
                "Calibration targets are empty."
            )

        if not np.isin(
            values,
            [0, 1],
        ).all():
            raise ValueError(
                "Calibration targets must contain only 0 and 1."
            )

        if len(
            np.unique(values)
        ) < 2:
            raise ValueError(
                "Calibration data must contain both classes."
            )

        return values.astype(int)

    def fit(
        self,
        raw_probabilities,
        y_true,
    ) -> "ProbabilityCalibrator":
        """
        Fit calibration using a separate calibration period.

        This data must NOT be the final test set.
        """

        probabilities = (
            self._validate_probabilities(
                raw_probabilities
            )
        )

        targets = (
            self._validate_targets(
                y_true
            )
        )

        if len(probabilities) != len(
            targets
        ):
            raise ValueError(
                "Probabilities and targets must have equal length."
            )

        if len(probabilities) < 30:
            raise ValueError(
                "At least 30 calibration observations are recommended."
            )

        if self.config.method == (
            "sigmoid"
        ):

            # Logistic regression needs a two-dimensional input.
            self.calibrator.fit(
                probabilities.reshape(
                    -1,
                    1,
                ),
                targets,
            )

        else:

            self.calibrator.fit(
                probabilities,
                targets,
            )

        self.is_fitted_ = True

        return self

    def transform(
        self,
        raw_probabilities,
    ) -> np.ndarray:
        """Transform raw probabilities into calibrated probabilities."""

        if not self.is_fitted_:
            raise RuntimeError(
                "Calibrator has not been fitted."
            )

        probabilities = (
            self._validate_probabilities(
                raw_probabilities
            )
        )

        if self.config.method == (
            "sigmoid"
        ):

            calibrated = (
                self.calibrator.predict_proba(
                    probabilities.reshape(
                        -1,
                        1,
                    )
                )[
                    :,
                    1,
                ]
            )

        else:

            calibrated = (
                self.calibrator.predict(
                    probabilities
                )
            )

        return np.clip(
            np.asarray(
                calibrated,
                dtype=float,
            ),
            self.config.clip_min,
            self.config.clip_max,
        )

    def fit_transform(
        self,
        raw_probabilities,
        y_true,
    ) -> np.ndarray:
        """Fit calibration and transform the calibration set."""

        self.fit(
            raw_probabilities,
            y_true,
        )

        return self.transform(
            raw_probabilities
        )


def calibration_metrics(
    y_true,
    probabilities,
    number_of_bins: int = 10,
) -> dict[str, float]:
    """
    Calculate probability calibration diagnostics.

    Metrics:

        Brier score
        Log loss
        Expected Calibration Error (ECE)

    Lower is better for all three metrics.
    """

    targets = np.asarray(
        y_true,
        dtype=float,
    ).reshape(-1)

    probs = np.asarray(
        probabilities,
        dtype=float,
    ).reshape(-1)

    if len(targets) != len(
        probs
    ):
        raise ValueError(
            "y_true and probabilities must have equal length."
        )

    valid = (
        np.isfinite(targets)
        & np.isfinite(probs)
    )

    targets = targets[valid].astype(int)
    probs = np.clip(
        probs[valid],
        1e-6,
        1 - 1e-6,
    )

    if len(targets) == 0:
        raise ValueError(
            "No valid calibration observations."
        )

    # Brier score.
    brier = float(
        np.mean(
            (
                probs
                - targets
            ) ** 2
        )
    )

    # Log loss.
    log_loss = float(
        -np.mean(
            targets
            * np.log(probs)
            + (
                1 - targets
            )
            * np.log(
                1 - probs
            )
        )
    )

    # Expected Calibration Error.
    bins = np.linspace(
        0,
        1,
        number_of_bins + 1,
    )

    ece = 0.0

    for lower, upper in zip(
        bins[:-1],
        bins[1:],
    ):

        if upper == 1:
            mask = (
                (probs >= lower)
                & (probs <= upper)
            )
        else:
            mask = (
                (probs >= lower)
                & (probs < upper)
            )

        if not mask.any():
            continue

        confidence = (
            probs[mask].mean()
        )

        accuracy = (
            targets[mask].mean()
        )

        weight = (
            mask.mean()
        )

        ece += (
            weight
            * abs(
                confidence
                - accuracy
            )
        )

    return {
        "brier_score": brier,
        "log_loss": log_loss,
        "ece": float(ece),
    }


def reliability_table(
    y_true,
    probabilities,
    number_of_bins: int = 10,
) -> pd.DataFrame:
    """
    Create a reliability/calibration table.

    Each row represents a probability bucket.
    """

    targets = np.asarray(
        y_true,
        dtype=int,
    ).reshape(-1)

    probs = np.asarray(
        probabilities,
        dtype=float,
    ).reshape(-1)

    if len(targets) != len(
        probs
    ):
        raise ValueError(
            "y_true and probabilities must have equal length."
        )

    bins = np.linspace(
        0,
        1,
        number_of_bins + 1,
    )

    rows = []

    for index in range(
        number_of_bins
    ):

        lower = bins[index]
        upper = bins[index + 1]

        if index == (
            number_of_bins - 1
        ):

            mask = (
                (probs >= lower)
                & (probs <= upper)
            )

        else:

            mask = (
                (probs >= lower)
                & (probs < upper)
            )

        count = int(
            mask.sum()
        )

        if count == 0:

            rows.append(
                {
                    "bin_lower": lower,
                    "bin_upper": upper,
                    "count": 0,
                    "mean_probability": np.nan,
                    "observed_frequency": np.nan,
                }
            )

            continue

        rows.append(
            {
                "bin_lower": lower,
                "bin_upper": upper,
                "count": count,
                "mean_probability": float(
                    probs[mask].mean()
                ),
                "observed_frequency": float(
                    targets[mask].mean()
                ),
            }
        )

    return pd.DataFrame(
        rows
    )


def evaluate_confidence_threshold(
    y_true,
    probabilities,
    thresholds: Optional[
        list[float]
    ] = None,
) -> pd.DataFrame:
    """
    Evaluate classification performance at different confidence
    thresholds.

    This is useful for deciding when the system should say:

        HIGH CONFIDENCE

    versus:

        NO HIGH-CONFIDENCE SETUP

    It does not assume that a particular threshold is optimal.
    """

    if thresholds is None:
        thresholds = [
            0.50,
            0.55,
            0.60,
            0.65,
            0.70,
            0.75,
            0.80,
            0.85,
            0.90,
            0.95,
        ]

    targets = np.asarray(
        y_true,
        dtype=int,
    ).reshape(-1)

    probs = np.asarray(
        probabilities,
        dtype=float,
    ).reshape(-1)

    if len(targets) != len(
        probs
    ):
        raise ValueError(
            "y_true and probabilities must have equal length."
        )

    rows = []

    for threshold in thresholds:

        confidence = np.maximum(
            probs,
            1 - probs,
        )

        selected = (
            confidence
            >= threshold
        )

        count = int(
            selected.sum()
        )

        if count == 0:

            rows.append(
                {
                    "threshold": threshold,
                    "observations": 0,
                    "coverage": 0.0,
                    "accuracy": np.nan,
                }
            )

            continue

        predicted = (
            probs[selected]
            >= 0.50
        ).astype(int)

        accuracy = float(
            np.mean(
                predicted
                == targets[selected]
            )
        )

        rows.append(
            {
                "threshold": threshold,
                "observations": count,
                "coverage": float(
                    count
                    / len(targets)
                ),
                "accuracy": accuracy,
            }
        )

    return pd.DataFrame(
        rows
    )
