"""
Model ensemble utilities for AI Swing Analyser.

Combines predictions from multiple independently trained models.

The ensemble supports:

    - Probability averaging
    - Weighted probability averaging
    - Return averaging
    - Range aggregation
    - Model disagreement measurement

IMPORTANT:

Ensemble weights must be selected using training/validation data
only. They must NEVER be optimized using the final test set.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

import numpy as np
import pandas as pd


@dataclass
class EnsembleConfig:
    """
    Configuration for model ensemble.
    """

    normalize_weights: bool = True

    default_weight: float = 1.0

    disagreement_threshold: float = 0.20


class ModelEnsemble:
    """
    Generic ensemble for model predictions.

    The ensemble itself does not train models.

    It receives predictions generated by independently trained
    models and combines them.
    """

    def __init__(
        self,
        config: Optional[
            EnsembleConfig
        ] = None,
    ) -> None:

        self.config = (
            config
            if config is not None
            else EnsembleConfig()
        )

        self.weights_: Dict[
            str,
            float,
        ] = {}

        self.is_fitted_: bool = False

    def set_weights(
        self,
        weights: Dict[str, float],
    ) -> "ModelEnsemble":
        """
        Set ensemble weights.

        Example:

            {
                "logistic": 0.25,
                "random_forest": 0.35,
                "gradient_boosting": 0.40,
            }

        The weights are normalized to sum to one unless disabled.
        """

        if not weights:
            raise ValueError(
                "At least one model weight is required."
            )

        cleaned = {}

        for name, weight in weights.items():

            if not np.isfinite(
                weight
            ):
                raise ValueError(
                    f"Invalid weight for {name}."
                )

            if weight < 0:
                raise ValueError(
                    f"Negative weight for {name}."
                )

            cleaned[name] = float(
                weight
            )

        if all(
            weight == 0
            for weight in cleaned.values()
        ):
            raise ValueError(
                "At least one ensemble weight must be positive."
            )

        if self.config.normalize_weights:

            total = sum(
                cleaned.values()
            )

            cleaned = {
                name: weight / total
                for name, weight
                in cleaned.items()
            }

        self.weights_ = cleaned

        self.is_fitted_ = True

        return self

    def equal_weights(
        self,
        model_names: list[str],
    ) -> "ModelEnsemble":
        """
        Assign equal weights.

        This is the safest initial baseline.
        """

        if not model_names:
            raise ValueError(
                "model_names cannot be empty."
            )

        weight = (
            1.0
            / len(model_names)
        )

        return self.set_weights(
            {
                name: weight
                for name in model_names
            }
        )

    def _validate_prediction_dict(
        self,
        predictions: Dict[str, np.ndarray],
    ) -> None:
        """Validate prediction dictionary."""

        if not predictions:
            raise ValueError(
                "No model predictions supplied."
            )

        lengths = []

        for name, values in predictions.items():

            array = np.asarray(
                values,
                dtype=float,
            ).reshape(-1)

            if len(array) == 0:
                raise ValueError(
                    f"Empty predictions from {name}."
                )

            if not np.isfinite(
                array
            ).all():
                raise ValueError(
                    f"Non-finite predictions from {name}."
                )

            lengths.append(
                len(array)
            )

        if len(
            set(lengths)
        ) != 1:
            raise ValueError(
                "All model prediction arrays must have equal length."
            )

    def _get_effective_weights(
        self,
        predictions: Dict[str, np.ndarray],
    ) -> Dict[str, float]:
        """
        Return weights for models actually present in predictions.
        """

        if not self.is_fitted_:
            names = list(
                predictions.keys()
            )

            return {
                name: 1.0 / len(names)
                for name in names
            }

        available = {
            name: weight
            for name, weight
            in self.weights_.items()
            if name in predictions
        }

        if not available:
            raise ValueError(
                "None of the configured ensemble models are present."
            )

        total = sum(
            available.values()
        )

        return {
            name: weight / total
            for name, weight
            in available.items()
        }

    def weighted_average(
        self,
        predictions: Dict[str, np.ndarray],
    ) -> np.ndarray:
        """
        Calculate weighted ensemble prediction.
        """

        self._validate_prediction_dict(
            predictions
        )

        weights = (
            self._get_effective_weights(
                predictions
            )
        )

        first = next(
            iter(predictions.values())
        )

        result = np.zeros(
            len(first),
            dtype=float,
        )

        for name, weight in (
            weights.items()
        ):

            result += (
                weight
                * np.asarray(
                    predictions[name],
                    dtype=float,
                )
            )

        return result

    def probability_average(
        self,
        probabilities: Dict[str, np.ndarray],
    ) -> np.ndarray:
        """
        Combine positive-class probabilities.

        The result is clipped to [0, 1].
        """

        result = self.weighted_average(
            probabilities
        )

        return np.clip(
            result,
            0.0,
            1.0,
        )

    def return_average(
        self,
        predictions: Dict[str, np.ndarray],
    ) -> np.ndarray:
        """
        Combine future-return predictions.
        """

        return self.weighted_average(
            predictions
        )

    def prediction_matrix(
        self,
        predictions: Dict[str, np.ndarray],
    ) -> pd.DataFrame:
        """
        Convert predictions into a model-by-observation matrix.
        """

        self._validate_prediction_dict(
            predictions
        )

        return pd.DataFrame(
            {
                name: np.asarray(
                    values,
                    dtype=float,
                ).reshape(-1)
                for name, values
                in predictions.items()
            }
        )

    def disagreement(
        self,
        predictions: Dict[str, np.ndarray],
    ) -> np.ndarray:
        """
        Measure model disagreement.

        Standard deviation is used as a simple first measure.

        High disagreement means the ensemble should be more
        cautious rather than automatically increasing confidence.
        """

        matrix = (
            self.prediction_matrix(
                predictions
            )
        )

        if matrix.shape[1] == 1:
            return np.zeros(
                len(matrix),
                dtype=float,
            )

        return matrix.std(
            axis=1
        ).to_numpy()

    def agreement_score(
        self,
        probabilities: Dict[str, np.ndarray],
    ) -> np.ndarray:
        """
        Calculate directional agreement between models.

        Returns approximately:

            +1 -> strong agreement on upward direction
             0 -> disagreement / neutral
            -1 -> strong agreement on downward direction
        """

        matrix = (
            self.prediction_matrix(
                probabilities
            )
        )

        directions = (
            np.where(
                matrix >= 0.50,
                1.0,
                -1.0,
            )
        )

        return directions.mean(
            axis=1
        )

    def range_average(
        self,
        ranges: Dict[
            str,
            pd.DataFrame,
        ],
    ) -> pd.DataFrame:
        """
        Combine multiple range-model predictions.

        Each dataframe must contain:

            Predicted_Lower_Return
            Predicted_Median_Return
            Predicted_Upper_Return
        """

        if not ranges:
            raise ValueError(
                "No range predictions supplied."
            )

        required = [
            "Predicted_Lower_Return",
            "Predicted_Median_Return",
            "Predicted_Upper_Return",
        ]

        for name, frame in ranges.items():

            missing = [
                column
                for column in required
                if column not in frame.columns
            ]

            if missing:
                raise ValueError(
                    f"Range model {name} is missing: {missing}"
                )

        lower_predictions = {
            name: frame[
                "Predicted_Lower_Return"
            ].to_numpy()
            for name, frame
            in ranges.items()
        }

        median_predictions = {
            name: frame[
                "Predicted_Median_Return"
            ].to_numpy()
            for name, frame
            in ranges.items()
        }

        upper_predictions = {
            name: frame[
                "Predicted_Upper_Return"
            ].to_numpy()
            for name, frame
            in ranges.items()
        }

        lower = self.weighted_average(
            lower_predictions
        )

        median = self.weighted_average(
            median_predictions
        )

        upper = self.weighted_average(
            upper_predictions
        )

        lower_final = np.minimum(
            lower,
            upper,
        )

        upper_final = np.maximum(
            lower,
            upper,
        )

        median_final = np.clip(
            median,
            lower_final,
            upper_final,
        )

        index = next(
            iter(ranges.values())
        ).index

        return pd.DataFrame(
            {
                "Predicted_Lower_Return": (
                    lower_final
                ),
                "Predicted_Median_Return": (
                    median_final
                ),
                "Predicted_Upper_Return": (
                    upper_final
                ),
            },
            index=index,
        )


def optimize_weights_from_validation(
    y_true: np.ndarray,
    model_predictions: Dict[
        str,
        np.ndarray,
    ],
    objective: str = "brier",
) -> Dict[str, float]:
    """
    Estimate non-negative ensemble weights using validation data.

    This is deliberately a simple, constrained optimizer.

    Supported objectives:

        brier
        mse

    IMPORTANT:
    This function MUST only receive validation predictions when
    selecting production ensemble weights.

    Never optimize weights using the final test set.
    """

    from scipy.optimize import minimize

    if not model_predictions:
        raise ValueError(
            "No model predictions supplied."
        )

    y = np.asarray(
        y_true,
        dtype=float,
    ).reshape(-1)

    prediction_names = list(
        model_predictions.keys()
    )

    prediction_arrays = []

    for name in prediction_names:

        values = np.asarray(
            model_predictions[name],
            dtype=float,
        ).reshape(-1)

        if len(values) != len(y):
            raise ValueError(
                f"Prediction length mismatch for {name}."
            )

        if not np.isfinite(
            values
        ).all():
            raise ValueError(
                f"Non-finite predictions for {name}."
            )

        prediction_arrays.append(
            values
        )

    matrix = np.column_stack(
        prediction_arrays
    )

    if objective not in {
        "brier",
        "mse",
    }:
        raise ValueError(
            "objective must be 'brier' or 'mse'."
        )

    def loss(weights):

        prediction = (
            matrix @ weights
        )

        if objective == "brier":

            return float(
                np.mean(
                    (
                        prediction
                        - y
                    ) ** 2
                )
            )

        return float(
            np.mean(
                (
                    prediction
                    - y
                ) ** 2
            )
        )

    initial = np.ones(
        matrix.shape[1]
    ) / matrix.shape[1]

    constraints = [
        {
            "type": "eq",
            "fun": lambda weights:
                np.sum(weights) - 1.0,
        }
    ]

    bounds = [
        (
            0.0,
            1.0,
        )
        for _ in prediction_names
    ]

    result = minimize(
        loss,
        initial,
        method="SLSQP",
        bounds=bounds,
        constraints=constraints,
        options={
            "maxiter": 500,
            "ftol": 1e-10,
        },
    )

    if not result.success:
        # Fall back to equal weights rather than producing
        # unstable or negative weights.
        equal = (
            1.0
            / len(prediction_names)
        )

        return {
            name: equal
            for name in prediction_names
        }

    weights = np.asarray(
        result.x,
        dtype=float,
    )

    weights = np.clip(
        weights,
        0.0,
        1.0,
    )

    total = weights.sum()

    if total <= 0:
        equal = (
            1.0
            / len(prediction_names)
        )

        return {
            name: equal
            for name in prediction_names
        }

    weights /= total

    return {
        name: float(weight)
        for name, weight
        in zip(
            prediction_names,
            weights,
        )
    }


def ensemble_confidence(
    probability: np.ndarray,
    disagreement: np.ndarray,
) -> np.ndarray:
    """
    Convert probability and model disagreement into a conservative
    confidence measure.

    This is NOT a calibrated probability.

    It is a diagnostic score intended to reduce confidence when
    models strongly disagree.
    """

    probability = np.asarray(
        probability,
        dtype=float,
    )

    disagreement = np.asarray(
        disagreement,
        dtype=float,
    )

    if probability.shape != (
        disagreement.shape
    ):
        raise ValueError(
            "probability and disagreement must have identical shapes."
        )

    directional_strength = (
        np.abs(
            probability
            - 0.50
        )
        * 2
    )

    disagreement_penalty = np.clip(
        disagreement
        / 0.20,
        0.0,
        1.0,
    )

    confidence = (
        directional_strength
        * (
            1
            - 0.5
            * disagreement_penalty
        )
    )

    return np.clip(
        confidence,
        0.0,
        1.0,
    )
